/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/models/Bell.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bell.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bell_Tower_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Bell_Tower_2.geometry} material={materials.Stone_Dark} />
        <mesh geometry={nodes.Bell_Tower_3.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Bell_Tower_4.geometry} material={materials.Wood_Side} />
        <mesh geometry={nodes.Bell_Tower_5.geometry} material={materials.Bell} />
        <mesh geometry={nodes.Bell_Tower_6.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Bell_Tower_7.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Bell_Tower_8.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Bell_Tower_9.geometry} material={materials.RoofTiles} />
        <mesh geometry={nodes.Bell_Tower_10.geometry} material={materials.Beige} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bell.glb')
